version: "3"
services:
  web:
    build: .
    container_name: pipeline_web
    entrypoint: /bin/sh
    # command: mix phx.server
    volumes:
      - .:/var/www/web
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true
    depends_on:
      - database
  database:
    container_name: pipeline_database
    image: postgres:13.6-alpine
    volumes:
      - ~/.docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
